[workspace]
version = "0.0.1"
edition = "2021"
resolver = "2"

members = [
    "rust/clients/host_agent",
    "rust/clients/orchestrator",
    "rust/services/authentication",
    "rust/services/workload",
    "rust/util_libs",
]

[workspace.dependencies]
async-nats = { version = "0.38.0", features = ["service"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3.31"
anyhow = "1.0"
serde = "1.0.215"
serde_json = "1.0.133"
dotenv = "0.15.0"
env_logger = "0.11.0"
log = "0.4.17"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
