FROM rust:1.85.0 AS builder

WORKDIR /usr/src/holo-dns
COPY . .

RUN --mount=type=cache,target=/root/.cargo \
    --mount=type=cache,target=/usr/src/holo-dns/target \
    cargo build --release && \
    cp /usr/src/holo-dns/target/release/holo-dns /usr/src/holo-dns/build

FROM gcr.io/distroless/cc
COPY --from=builder /usr/src/holo-dns/build /holo-dns

EXPOSE 3000
CMD ["/holo-dns"]