[package]
name = "holo-public-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
actix-multipart = "0.7.2"
actix-cors = "0.7.1"
futures-util = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
config = "0.15.11"
dotenvy = "0.15.7"
jsonwebtoken = "9.3.1"
chrono = "0.4.40"
utoipa = "5.3.1"
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
mongodb = "2.1" # todo: need to update to 3
bson = { version = "2.13.0", features = ["chrono-0_4"] }
tokio = { version = "1.44.1", features = ["full"] }
anyhow = "1.0.97"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
redis = { version = "0.29.1", features = ["tls-native-tls", "tokio-native-tls-comp"] }
deadpool-redis = "0.20.0"
cron = "0.15.0"
blake3 = "1.6.1"