[package]
name = "inventory"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
async-nats = { workspace = true }
bson = { workspace = true }
log = { workspace = true }
mongodb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hpos-hal = { workspace = true }
util_libs = { path = "../../util_libs" }

[dev-dependencies]
tempfile = "3.8"

[features]
# tests_integration_inventory_service = ["util_libs/tests_integration_mongodb"]