# see https://nexte.st/docs/configuration/?h=config for a reference

[profile.default]
retries = { backoff = "exponential", count = 5, delay = "1s", jitter = true }
slow-timeout = { period = "60s", terminate-after = 2 }
