[package]
name = "nixos-contain-rs"
edition = "2024"
version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "nixos-contain-rs"
path = "src/bin/nixos-contain.rs"

[dependencies]
anyhow = { workspace = true }
