name: Holo DNS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  RUST_VERSION: 1.85.0

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ env.RUST_VERSION }}

      - name: Cache Rust Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./target
          key: rust-holo-dns-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            rust-holo-dns-
            rust-

      - name: Build Project
        run: cargo build -p holo-dns --verbose

      - name: Run Tests
        run: cargo test -p holo-dns --verbose

      - name: Run Clippy
        run: cargo clippy -p holo-dns -- -D warnings

      - name: Run Linter
        run: cargo fmt -p holo-dns -- --check

  CD:
    name: Deploy to Dev
    needs: CI
    uses: ./.github/workflows/deploy_to_digital_ocean.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: dev
      project: holo-dns
      droplets: '["46.101.64.62"]' # json array
      port: 53
    secrets:
      DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
