name: Holo DNS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  RUST_VERSION: 1.85.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ env.RUST_VERSION }}
          
      - name: Cache Rust Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./target
          key: rust-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            rust-

      - name: Build Project
        run: cargo build --verbose

  deployDev:
    name: Deploy to Dev
    needs: 
      - build
    uses: ./.github/workflows/deploy_to_do_droplet.yml
    with:
      environment: dev
      project: holo-dns
      working_directory: rust/holo-dns
    secrets:
      DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}