name: Holo DNS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  RUST_VERSION: 1.85.0

jobs:
  CI:
    name: CI
    uses: ./.github/workflows/shared/ci.yml
    with:
      project: holo-dns

  CD_DEV:
    name: CD [Dev]
    needs: CI
    uses: ./.github/workflows/shared/deploy_to_digital_ocean.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: dev
      project: holo-dns
      droplets: '["46.101.64.62"]' # json array
      port: 53
    secrets:
      DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
