name: Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  #holo-dns
  HOLO_DNS_CI:
    name: holo-dns
    uses: ./.github/workflows/reuseable_ci.yml
    with:
      project: holo-dns

  HOLO_DNS_DEPLOY_DEV:
    name: holo-dns Dev
    needs: HOLO_DNS_CI
    uses: ./.github/workflows/reuseable_do_deployment.yml
    if: github.ref == 'refs/heads/main'
    with:
      project: holo-dns
      environment: dev
      droplets: '["ns1.web-bridge.holo.host"]' # json array
      dockerArgs: "-p 53:53/tcp -p 53:53/udp" # docker args
    secrets:
      DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

  # holo-gateway
  HOLO_GATEWAY_CI:
    name: holo-gateway
    uses: ./.github/workflows/reuseable_ci.yml
    with:
      project: holo-gateway

  HOLO_GATEWAY_DEPLOY_DEV:
    name: holo-gateway Dev
    needs: HOLO_GATEWAY_CI
    uses: ./.github/workflows/reuseable_do_deployment.yml
    if: github.ref == 'refs/heads/main'
    with:
      project: holo-gateway
      environment: dev
      droplets: '["api.dev.holo.host"]'
      dockerArgs: "-p 8000:8000 -v /root/nats.password:/root/nats.password"
      dockerCustomCommand: "/build --nats-url wss://nats-server-0.holotest.dev:443 --nats-user gateway --nats-password-file /root/nats.password"
    secrets:
      DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

  # holo-public api
  HOLO_PUBLIC_API_CI:
    name: holo-public-api
    uses: ./.github/workflows/reuseable_ci.yml
    with:
      project: holo-public-api
      mongo: true
      redis: true

  HOLO_PUBLIC_API_DEPLOY_DEV:
    name: holo-public-api Dev
    needs: HOLO_PUBLIC_API_CI
    uses: ./.github/workflows/reuseable_do_deployment.yml
    # if: github.ref == 'refs/heads/main'
    with:
      project: holo-public-api
      environment: dev
      droplets: '["api.dev.holo.host"]'
      dockerArgs: "-p 3000:3000 -v /tmp:/tmp -v /srv/holo-blobstore:/srv/holo-blobstore" # docker args
    secrets:
      DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
