name: Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  #holo-dns
  HOLO_DNS_CI:
    name: holo-dns
    uses: ./.github/workflows/reuseable_ci.yml
    with:
      project: holo-dns

  HOLO_DNS_DEPLOY_DEV:
    name: holo-dns Dev
    needs: HOLO_DNS_CI
    uses: ./.github/workflows/reuseable_do_deployment.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: dev
      project: holo-dns
      droplets: '["ns1.web-bridge.holo.host"]' # json array
      port: 53
    secrets:
      DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

  
  # holo-gateway
  HOLO_GATEWAY_CI:
    name: holo-gateway
    uses: ./.github/workflows/reuseable_ci.yml
    with:
      project: holo-gateway

  HOLO_GATEWAY_DEPLOY_DEV:
    name: holo-gateway Dev
    needs: HOLO_GATEWAY_CI
    uses: ./.github/workflows/reuseable_do_deployment.yml
    if: github.ref == 'refs/heads/main'
    with:
      environment: dev
      project: holo-gateway
    secrets:
      DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
