on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
        description: Rust package to build and deploy (assumes path is rust/{project})
      environment:
        required: true
        type: string
        description: Environment to deploy to, this maps to github environments
      droplets:
        required: false
        type: string
        description: |
          json list of droplets to deploy the docker image to.
          These droplets will be updated to use the new image automatically.
      dockerArgs:
        required: false
        type: string
        description: Docker arguments to pass when starting the container
    secrets:
      DIGITAL_OCEAN_TOKEN:
        required: true
      SSH_KEY:
        required: false
      SSH_USERNAME:
        required: false
env:
  RUST_VERSION: 1.85.0

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create cache directories
        run: |
          mkdir -p ${{ github.workspace }}/docker-cargo
          mkdir -p ${{ github.workspace }}/docker-target
          mkdir -p ${{ github.workspace }}/docker-buildx-cache

      - name: Cache Docker Build
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/docker-cargo
            ${{ github.workspace }}/docker-target
            ${{ github.workspace }}/docker-buildx-cache
          key: docker-${{ inputs.project }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            docker-${{ inputs.project }}-
            docker-

      - name: Map Docker Cache
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "${{ github.workspace }}/docker-cargo": "/root/.cargo",
              "${{ github.workspace }}/docker-target": "/usr/src/target"
            }
          skip-extraction: ${{ steps.cache-docker.outputs.cache-hit }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PROJECT_NAME=${{ inputs.project }}
          context: .
          load: true
          push: false
          cache-from: type=local,dest=${{ github.workspace }}/docker-buildx-cache
          cache-to: type=local,mode=max,src=${{ github.workspace }}/docker-buildx-cache .
          platforms: linux/amd64
          tags: registry.digitalocean.com/holo-host/${{ inputs.project }}:${{ inputs.environment }}

      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push Docker Image to DO Container Registry
        run: docker push registry.digitalocean.com/holo-host/${{ inputs.project }}:${{ inputs.environment }}

      # removes built image so it is not stored in the cache
      - name: Clean up
        run: rm -f ${{ github.workspace }}/docker-target/release/${{ inputs.project }}

  update-droplets:
    name: Update Droplets
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ inputs.droplets }}
    strategy:
      matrix:
        droplet: ${{ fromJson(inputs.droplets) }}
    steps:
      - name: Refresh Droplets
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ matrix.droplet }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # stop and remove old container
            docker stop ${{ inputs.project }}
            docker rm ${{ inputs.project }}

            # pull new image and run it
            docker pull registry.digitalocean.com/holo-host/${{ inputs.project }}:${{ inputs.environment }}
            docker run -d \
              --restart unless-stopped \
              --env-file .env \
              --name ${{ inputs.project }} \
              ${{ inputs.dockerArgs }} \
              registry.digitalocean.com/holo-host/${{ inputs.project }}:${{ inputs.environment }}

            # clean up unused images
            docker system prune -a -f
